### TensorFlow 2.0 编程基础

In [1]:
import tensorflow as tf 
print("Tensorflow的版本是：",tf.__version__);

Tensorflow的版本是： 2.0.0


In [3]:
# 定义两个常量进行加操作
node1 = tf.constant([[3.0,1.5],[2.5,6.0]],tf.float32)
node2 = tf.constant([[4.0,1.0],[5.0,2.5]])
node3 = tf.add(node1,node2)

node3

<tf.Tensor: id=5, shape=(2, 2), dtype=float32, numpy=
array([[7. , 2.5],
       [7.5, 8.5]], dtype=float32)>

In [4]:
# 2.0 中直接获取一个Tensor的值
print(node3.numpy())

[[7.  2.5]
 [7.5 8.5]]


#### 类型转换

In [6]:
a = tf.constant([1,2])
b = tf.constant([2.0,3.0])

a = tf.cast(a,tf.float32)

result = tf.add(a,b)
result

array([3., 5.], dtype=float32)

#### 2.0 中的常量

```
 tf.constant(
    value,
    dtype=None,
    shape=None,
    name='Const'
)
```

In [9]:
c = tf.constant([1,2,3,4,5,6],shape=[2,3])
c 

<tf.Tensor: id=18, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

创建常量时如果指定的张量的形状，那么就会做对应的reshape操作。

#### 2.0 中变量
```
tf.Variable(
    initial_value,
    dtype=None,
    shape=None,
    trainable=True,
    name='Variable'
)
```

TensorFlow中的变量是一种特殊的设计，是可以被机器优化过程中自动改变值的张量。在变量被创建后，一般无需人工进行赋值，系统会根据算法模型，在训练优化过程中自动调整变量的值。

In [10]:
v1 = tf.Variable([1,2])
v1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

变量在创建时必须确定初始值。

##### 变量的赋值

In [11]:
v = tf.Variable(5)
v.assign(v+1)
v 

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>

In [13]:
v.assign_add(1) # 加法赋值
v 

v.assign_sub(2) # 减法赋值
v 

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>

#### 在TensorFlow 2.0 中实现1.x的静态图执行模式

* TensorFlow 2.0 代码的执行机制默认采用的是Eager Execution（动态图执行）；
* 1.x的代码主要是基于传统的Graph Execution（静态图执行），这种存在方式灵活性差、入门门槛高、无法使用Python原生控制语句弊端；
* 但是，静态图的执行机制效率更高，所以我们一般使用静态图执行模式部署我们开发好的模型。



In [33]:
import tensorflow.compat.v1 as tf_v1 
tf_v1.disable_eager_execution() # 禁用2.0中的动态图执行模式

In [34]:
num1 = tf_v1.constant(3.0,tf_v1.float32,name='num1')
num2 = tf_v1.constant(4.0,tf_v1.float32,name='num4')
num3 = tf_v1.add(num1,num2)
print(num3)

Tensor("Add_5:0", shape=(), dtype=float32)


由于采用的是静态图执行模式，这是仅仅是建立了计算图，它并没有执行。

In [35]:
sess = tf_v1.Session()
print(sess.run(node3))

sess.close()

AttributeError: Tensor.graph is meaningless when eager execution is enabled.